version: 2.1

jobs:
  deploy:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Set up AWS credentials
          command: echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY > ~/.env
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Plan
          command: terraform plan 
      # - run:
      #     name: Terraform Apply
      #     command: terraform apply -auto-approve tfplan